management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /MyActuator
  server:
    port: 12584
    address: 127.0.0.1

server:
  port: 8511

app-config:
  grpc-server-name: localhost
  grpc-server-port: 8289

grpc:
  server:
    max-message-size: 5194304
#
#grpc:
#  port: 6565
#
#app-config:
#  grpc-server-name: localhost
#  grpc-server-port: 6565