management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /MyActuator
  server:
    port: 12584
    address: 127.0.0.1

server:
  port: 8511

app-config:
  grpc-server-name: 222.200.184.74
  grpc-server-port: 8289
  max-message-size: 1073741824
